<h3>User Role Editor</h3>
<p>Select role and its capabilities in the list.</p>
<div>Select Role :</div>
<h3>Capabilities</h3>


<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'mhr-acl/default',
    array(
        'action'     => 'add',
        'controller' => 'role'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>


<ul>
    <li>
        <input type="checkbox" name="level-1">Level 1</input>
        <ul>
            <li>
                <input type="checkbox" name="level-2">Level 2</input>
                <ul>
                    <li>
                        <input type="checkbox" name="level-3">Level 3</input>
                    </li>
                    <li>
                        <input type="checkbox" name="level-3">Level 3</input>
                    </li>
                    <li>
                        <input type="checkbox" name="level-3">Level 3</input>
                    </li>
                    <li>
                        <input type="checkbox" name="level-3">Level 3</input>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

<script>
    $('input[name^="level"]').click(function () {
        $(this).parent().find('input[name^=level]').prop('checked', this.checked);

        if (!this.checked) {
            var level = this.name.substring(this.name.length - 1);
            for (var i = level - 1; i > 0; i--) {
                $('input[name="level-' + i + '"]').prop('checked', false);
            }
        }
    });
</script>
